### ISSUE TITLE
Download it successfully, but doesn't work

### ISSUE THREAD

**Issue by wanmaoor** [pod4g/hiper#25]
I followed the example, input`hiper baidu.com`. and then,no any response and doesn't show any details.

**Comment by wanmaoor** [comment]
I guess that whether I skip the download of Chromium

**Comment by Brownyuan** [comment]
Same here.Install on ubuntu server with "sudo npm install -g hiper --unsafe-perm=true --allow-root", input "hiper www.github.com" no any response and show nothing.

**Comment by jojonothing** [comment]
@Brownyuan Same problem.

**Comment by dlowder** [comment]
What version of Node and NPM are you running?

**Comment by MattMattV** [comment]
Using node 10.5.0 on Manjaro I face the same issue, the command output nothing and finish quietly with a 0 exit code.

But if I pass the the full path to a chrome executable with `-e` the command seems to loop infinitely.

**Comment by Brownyuan** [comment]
* NPM version: 5.6.0
* Node version: v8.11.3

**Comment by lilywang711** [comment]
NPM version: 6.1.0
Node version: v10.4.1

Same problem

**Comment by dlowder** [comment]
I wasn't able to run Hiper out of the box following the documentation on Ubuntu Server 18.04. After some investigating and attempting to replicate what @wanmaoor and @Brownyuan reported, I was able to get it working by installing the required dependencies for Puppeteer to work which Hiper is dependent on. Full log available below.

```
$ npm -v
6.1.0
$ node -v
v8.10.0
$ uname -a
Linux safehouse 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ sudo npm install -g hiper --unsafe-perm=true --allow-root
$ hiper -v
0.0.16
$ hiper -n 1 https://www.github.com/
# no output (chromium failed to run)
$ sudo apt-get install libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0
$ sudo chmod -R o+rx /usr/local/lib/node_modules/hiper/node_modules/puppeteer/.local-chromium
```
These steps may be different depending on how you installed Hiper or what OS you're using.

Ideally Hiper should improve error handling so that if Puppeteer (Chromium) fails under the hood the exception bubbles up.

References:
- https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by hanshou101** [comment]
> I guess that whether I skip the download of Chromium

I'm using Hiper on Windows 10 .
When I fisrt  install it  :  $ npm install hiper -g .

The terminal idle  in    "downloading  chromium"  ,  maybe  blocked by bad network state.
I     interrrupted my terminal.

Then,   I  meet  the same situation of you .
When I input   "hiper baidu.com"  ,  it has no any response.

And then ,I  uninstall hiper   ,  and   reinstall it .
This time ,  I installed whole  chromium       ( because I  switched  ShadowSocks  to  Global Mode  ,  it was PAC mode before .)

Finnally,   Hiper works  perfectly in my  computer,  with Windows 10 OS .

:-)

**Comment by wanmaoor** [comment]
> > I guess that whether I skip the download of Chromium
> 
> I'm using Hiper on Windows 10 .
> When I fisrt install it : $ npm install hiper -g .
> 
> The terminal idle in "downloading chromium" , maybe blocked by bad network state.
> I interrrupted my terminal.
> 
> Then, I meet the same situation of you .
> When I input "hiper baidu.com" , it has no any response.
> 
> And then ,I uninstall hiper , and reinstall it .
> This time , I installed whole chromium ( because I switched ShadowSocks to Global Mode , it was PAC mode before .)
> 
> Finnally, Hiper works perfectly in my computer, with Windows 10 OS .
> 
> :-)

ok, it's done

**Comment by wanmaoor** [comment]
this issue could be closed
